import Head from 'next/head';
import Room from './room';

export default function Home() {
	return (
		<div>
			<Head>
				<title>NU SPACE ROOM</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Room />
		</div>
	);
}
